# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1c8c481c-0180-4b3a-bc28-6d2a1bbe9bf8'
  imageRepository: 'golangsimpleweb'
  containerRegistry: 'qtrungtestcr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push container image
  jobs:
  - job: Build
    displayName: Build container image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: 'sonarcloud-conn'
        organization: 'thehaohcm-organization'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'thehaohcm_golang-simpleweb'
        cliProjectName: 'golang-simpleweb'
        cliSources: '.'
    - task: SonarCloudAnalyze@1
      displayName: 'Run Code Analysis'
    
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: 'latest'
- stage: UATDeploy
  displayName: Deploy into UAT server
  jobs:
  - deployment: Deploy container image into UAT Server
    environment: 'uat-deploy-approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: uat-deploy-test1'
            inputs:
              azureSubscription: 'Azure subscription 1 (63b30e78-e8f8-4e25-8ece-3cc63e2199cc)'
              appType: webAppContainer
              WebAppName: 'uat-deploy-test1'
              DockerNamespace: qtrungtestcr.azurecr.io
              DockerRepository: golangsimpleweb
              DockerImageTag: latest
- stage: PRODDeploy
  displayName: Deploy into PRODUCT server
  jobs:
  - deployment: Deploy container image into PRODUCT server
    environment: 'prod-deploy-approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: prod-deploy-test1'
            inputs:
              azureSubscription: 'Azure subscription 1 (63b30e78-e8f8-4e25-8ece-3cc63e2199cc)'
              appType: webAppContainer
              WebAppName: 'prod-deploy-test1'
              DockerNamespace: qtrungtestcr.azurecr.io
              DockerRepository: golangsimpleweb
              DockerImageTag: latest  